FROM opti-erigon:latest

# FROM ethereumoptimism/reference-optimistic-geth:latest

# RUN apk add --no-cache jq

COPY entrypoint_l2.sh /entrypoint.sh

VOLUME ["/db"]

ENTRYPOINT ["/bin/sh", "/entrypoint.sh"]
